# Generated by Django 3.1.7 on 2021-09-22 16:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_company', models.BooleanField(default=False, verbose_name='Это компания')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании')),
                ('patronymic', models.CharField(max_length=255, null=True, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, default='defaultuser.png', null=True, upload_to=main.models.image_directory_path, verbose_name='Изображение профиля')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('phone_number', models.CharField(max_length=12, null=True, verbose_name='Номер телефона')),
                ('birthdate', models.DateField(default=datetime.date.today, null=True, verbose_name='Дата рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('logo', models.ImageField(default='defaultuser.png', upload_to=main.models.image_directory_path, verbose_name='Логотип компании')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('about', models.TextField(verbose_name='О компании')),
                ('contact_patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
