# Generated by Django 3.1.7 on 2021-09-27 17:04

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, default='defaultuser.png', null=True, upload_to=main.models.image_directory_path, verbose_name='Логотип компании'),
        ),
    ]
