# Generated by Django 3.1.7 on 2021-09-28 16:12

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210928_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(default='defaultuser.png', upload_to=main.models.image_directory_path, verbose_name='Логотип компании'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='defaultuser.png', upload_to=main.models.image_directory_path, verbose_name='Изображение профиля'),
        ),
    ]
