# Generated by Django 3.1.7 on 2021-09-28 16:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210928_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(default='defaultuser.png', upload_to=django.core.files.storage.FileSystemStorage(base_url='/media/profile/', location='F:\\Workspace\\PyCharm projects\\workShip django\\workShip\\media/profile/'), verbose_name='Логотип компании'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='defaultuser.png', upload_to=django.core.files.storage.FileSystemStorage(base_url='/media/profile/', location='F:\\Workspace\\PyCharm projects\\workShip django\\workShip\\media/profile/'), verbose_name='Изображение профиля'),
        ),
    ]
