# Generated by Django 3.1.7 on 2021-09-28 17:34

import django.core.files.storage
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210928_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(default='defaultuser.png', storage=django.core.files.storage.FileSystemStorage(base_url='/media/profile/', location='F:\\Workspace\\PyCharm projects\\workShip django\\workShip\\media/profile/'), upload_to=main.models.image_directory_path, verbose_name='Логотип компании'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='defaultuser.png', storage=django.core.files.storage.FileSystemStorage(base_url='/media/profile/', location='F:\\Workspace\\PyCharm projects\\workShip django\\workShip\\media/profile/'), upload_to=main.models.image_directory_path, verbose_name='Изображение профиля'),
        ),
    ]
