# Generated by Django 3.2.7 on 2021-09-14 07:01

import django.core.files.storage
from django.db import migrations, models
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='image',
            field=models.ImageField(default='static/defaultuser.png', storage=django.core.files.storage.FileSystemStorage(base_url='/media/summaries/', location='/home/dnechiporenko/PyCharmProjects/workShip/workShip/media/summaries/'), upload_to=education.models.image_directory_path),
        ),
    ]
