# Generated by Django 3.1.7 on 2021-09-28 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_auto_20210927_2125'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('new', models.BooleanField(default=True, verbose_name='Новый отклик')),
                ('approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summaries.summary')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy')),
            ],
        ),
    ]
