# Generated by Django 3.1.7 on 2021-09-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_vacancyresponses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancyresponses',
            options={'ordering': ['-time_create'], 'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
    ]
