# Generated by Django 3.1.7 on 2021-09-23 14:26

import django.core.files.storage
from django.db import migrations, models
import vacancies.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_remove_vacancy_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(default='defaultuser.png', storage=django.core.files.storage.FileSystemStorage(base_url='/media/summaries/', location='F:\\Workspace\\PyCharm projects\\workShip django\\workShip\\media/summaries/'), upload_to=vacancies.models.image_directory_path, verbose_name='Изображение'),
        ),
    ]
