# Generated by Django 3.1.7 on 2021-09-03 15:02

import django.core.files.storage
from django.db import migrations, models
import vacancies.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_auto_20210415_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.TextField(default='Без описания', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(default='static/defaultuser.png', storage=django.core.files.storage.FileSystemStorage(base_url='/media/summaries/', location='F:\\Workspace\\PyCharm projects\\workShip django\\workShip\\media/summaries/'), upload_to=vacancies.models.image_directory_path),
        ),
    ]
