# Generated by Django 3.1.7 on 2021-09-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20210903_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='description',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='contract_term',
            field=models.CharField(default='', max_length=255, verbose_name='Срок контракта'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='landing',
            field=models.CharField(default='', max_length=255, verbose_name='Место посадки'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vessel_type',
            field=models.CharField(default='', max_length=255, verbose_name='Тип судна'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='date_start',
            field=models.DateField(verbose_name='Дата посадки'),
        ),
    ]
