# Generated by Django 3.1.7 on 2021-09-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20210928_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyresponses',
            name='from_company',
            field=models.BooleanField(default=True, verbose_name='Заявка от компании'),
        ),
    ]
