# Generated by Django 3.2.7 on 2021-09-21 05:07

import django.core.files.storage
from django.db import migrations, models
import vacancies.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_auto_20210914_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(default='defaultuser.png', storage=django.core.files.storage.FileSystemStorage(base_url='/media/summaries/', location='/home/dnechiporenko/PyCharmProjects/workShip/workShip/media/summaries/'), upload_to=vacancies.models.image_directory_path, verbose_name='Изображение'),
        ),
    ]
