# Generated by Django 3.1.7 on 2021-04-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('job', models.CharField(max_length=255, verbose_name='Зарплата')),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('salary_min', models.CharField(max_length=255, verbose_name='Компания')),
                ('salary_max', models.CharField(max_length=255, verbose_name='Компания')),
                ('extra', models.CharField(max_length=255, verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
