# Generated by Django 3.1.7 on 2021-09-27 17:04

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import summaries.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('job', models.CharField(max_length=255, verbose_name='Должность')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('salary_min', models.CharField(max_length=255, verbose_name='Зарплата от')),
                ('salary_max', models.CharField(max_length=255, verbose_name='Зарплата до')),
                ('extra', models.TextField(default='Без описания', verbose_name='Дополнительно')),
                ('image', models.ImageField(default='static/defaultuser.png', storage=django.core.files.storage.FileSystemStorage(base_url='/media/summaries/', location='F:\\Workspace\\PyCharm projects\\workShip django\\workShip\\media/summaries/'), upload_to=summaries.models.image_directory_path)),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
