# Generated by Django 3.1.7 on 2021-09-22 15:57

import django.core.files.storage
from django.db import migrations, models
import summaries.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('job', models.CharField(max_length=255, verbose_name='Должность')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('salary_min', models.CharField(max_length=255, verbose_name='Зарплата от')),
                ('salary_max', models.CharField(max_length=255, verbose_name='Зарплата до')),
                ('extra', models.TextField(default='Без описания', verbose_name='Дополнительно')),
                ('image', models.ImageField(default='static/defaultuser.png', storage=django.core.files.storage.FileSystemStorage(base_url='/media/summaries/', location='F:\\Workspace\\PyCharm projects\\workShip django\\workShip\\media/summaries/'), upload_to=summaries.models.image_directory_path)),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
