# Generated by Django 3.1.7 on 2021-04-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='date',
        ),
        migrations.AlterField(
            model_name='summary',
            name='extra',
            field=models.TextField(verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='job',
            field=models.CharField(max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='salary_max',
            field=models.CharField(max_length=255, verbose_name='Зарплата до'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='salary_min',
            field=models.CharField(max_length=255, verbose_name='Зарплата от'),
        ),
    ]
