# Generated by Django 3.1.7 on 2021-09-03 15:02

import django.core.files.storage
from django.db import migrations, models
import summaries.models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_auto_20210415_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='image',
            field=models.ImageField(default='static/defaultuser.png', storage=django.core.files.storage.FileSystemStorage(base_url='/media/summaries/', location='F:\\Workspace\\PyCharm projects\\workShip django\\workShip\\media/summaries/'), upload_to=summaries.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='summary',
            name='extra',
            field=models.TextField(default='Без описания', verbose_name='Дополнительно'),
        ),
    ]
