# Generated by Django 3.1.7 on 2021-09-02 16:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seamandocument',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media//', location='F:\\Workspace\\PyCharm projects\\workShip django\\workShip\\media/'), upload_to='image_directory_path'),
        ),
    ]
