# Generated by Django 3.1.7 on 2021-09-02 16:42

import django.core.files.storage
from django.db import migrations, models
import seaman.models


class Migration(migrations.Migration):

    dependencies = [
        ('seaman', '0002_auto_20210902_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seamandocument',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/seaman/', location='F:\\Workspace\\PyCharm projects\\workShip django\\workShip\\media/seaman/'), upload_to=seaman.models.image_directory_path),
        ),
    ]
