# Generated by Django 3.1.7 on 2021-09-23 14:26

import django.core.files.storage
from django.db import migrations, models
import seaman.models


class Migration(migrations.Migration):

    dependencies = [
        ('seaman', '0002_auto_20210923_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seamanblank',
            name='file',
            field=models.FileField(default='static/defaultuser.png', storage=django.core.files.storage.FileSystemStorage(base_url='/media/seaman/blanks/', location='F:\\Workspace\\PyCharm projects\\workShip django\\workShip\\media/seaman/blanks/'), upload_to=seaman.models.blank_directory_path),
        ),
        migrations.AlterField(
            model_name='seamandocument',
            name='image',
            field=models.ImageField(default='static/defaultuser.png', storage=django.core.files.storage.FileSystemStorage(base_url='/media/seaman/', location='F:\\Workspace\\PyCharm projects\\workShip django\\workShip\\media/seaman/'), upload_to=seaman.models.image_directory_path),
        ),
    ]
