# Generated by Django 3.2.7 on 2021-09-14 07:01

import django.core.files.storage
from django.db import migrations, models
import seaman.models


class Migration(migrations.Migration):

    dependencies = [
        ('seaman', '0004_auto_20210903_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seamanblank',
            name='file',
            field=models.FileField(default='static/defaultuser.png', storage=django.core.files.storage.FileSystemStorage(base_url='/media/seaman/blanks/', location='/home/dnechiporenko/PyCharmProjects/workShip/workShip/media/seaman/blanks/'), upload_to=seaman.models.blank_directory_path),
        ),
        migrations.AlterField(
            model_name='seamandocument',
            name='image',
            field=models.ImageField(default='static/defaultuser.png', storage=django.core.files.storage.FileSystemStorage(base_url='/media/seaman/', location='/home/dnechiporenko/PyCharmProjects/workShip/workShip/media/seaman/'), upload_to=seaman.models.image_directory_path),
        ),
    ]
